packages:
  # Các dự án hiện tại
  - "apps/*"
  - "apps/core-apps/*"
  - "packages/*"
  
  # Các dự án từ nurmandev
  - "apps/external/prodevs"
  - "apps/external/fortress"
  - "apps/external/market-api"
  - "apps/external/graph-ai/Frontend"
  - "apps/external/graph-ai/Backend"
  - "apps/external/nurman-backend"
  - "apps/external/innovatics"
  - "apps/external/academy"
  - "apps/external/landing/backend"
  - "apps/external/landing/frontend"
  - "apps/external/social"
  - "apps/external/chat"
  - "apps/external/market-admin"
  - "apps/external/expenses"
  - "apps/external/paylock"
  - "apps/external/shammarianas/functions"
  - "apps/external/shammarianas"
  - "apps/external/event"
  - "apps/external/invest-backend"
  - "apps/external/todo/backend"
  - "apps/external/todo/frontend"
  - "apps/external/anonymous-voice/anonymous-voice-server"
  - "apps/external/anonymous-voice/anonymous-voice"
  - "apps/external/academy-backend"
  - "apps/external/crypto"
  - "apps/external/bank-app-frontend"
  - "apps/external/invest-frontend/investment-client"
  - "apps/external/invest-frontend/investment-backend"
  - 'packages/scripts-utils'
