'use strict';
/**
 * @lkvip/constants — errors.js
 * Standardized error codes and HTTP status codes for the LKVIP platform.
 *
 * Error code format: DOMAIN_REASON (e.g. AUTH_TOKEN_EXPIRED, USER_NOT_FOUND)
 */

/**
 * Application-level error codes.
 * These are returned in API responses alongside HTTP status codes.
 * @type {Record<string, string>}
 */
const ERROR_CODES = {
  // Auth errors
  AUTH_TOKEN_MISSING:      'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID:      'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED:      'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_ROLE:  'AUTH_INSUFFICIENT_ROLE',
  AUTH_PROJECT_MISMATCH:   'AUTH_PROJECT_MISMATCH',
  AUTH_ACCOUNT_INACTIVE:   'AUTH_ACCOUNT_INACTIVE',
  AUTH_ACCOUNT_BANNED:     'AUTH_ACCOUNT_BANNED',
  AUTH_INVALID_CREDENTIALS:'AUTH_INVALID_CREDENTIALS',
  AUTH_MAX_ATTEMPTS:       'AUTH_MAX_ATTEMPTS',
  AUTH_OTP_INVALID:        'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED:        'AUTH_OTP_EXPIRED',

  // User errors
  USER_NOT_FOUND:          'USER_NOT_FOUND',
  USER_ALREADY_EXISTS:     'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN:        'USER_EMAIL_TAKEN',
  USER_USERNAME_TAKEN:     'USER_USERNAME_TAKEN',

  // Wallet / Payment errors
  WALLET_INSUFFICIENT_FUNDS: 'WALLET_INSUFFICIENT_FUNDS',
  WALLET_TRANSACTION_FAILED: 'WALLET_TRANSACTION_FAILED',
  PAYMENT_GATEWAY_ERROR:     'PAYMENT_GATEWAY_ERROR',
  PAYMENT_AMOUNT_INVALID:    'PAYMENT_AMOUNT_INVALID',
  PAYMENT_AMOUNT_TOO_LOW:    'PAYMENT_AMOUNT_TOO_LOW',
  PAYMENT_AMOUNT_TOO_HIGH:   'PAYMENT_AMOUNT_TOO_HIGH',

  // KYC errors
  KYC_NOT_SUBMITTED:       'KYC_NOT_SUBMITTED',
  KYC_PENDING:             'KYC_PENDING',
  KYC_REJECTED:            'KYC_REJECTED',
  KYC_DOCUMENT_INVALID:    'KYC_DOCUMENT_INVALID',

  // Game errors
  GAME_SESSION_NOT_FOUND:  'GAME_SESSION_NOT_FOUND',
  GAME_PROVIDER_ERROR:     'GAME_PROVIDER_ERROR',
  GAME_MAINTENANCE:        'GAME_MAINTENANCE',

  // General errors
  VALIDATION_ERROR:        'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED:     'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND:      'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT:       'RESOURCE_CONFLICT',
  INTERNAL_SERVER_ERROR:   'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE:     'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE:        'MAINTENANCE_MODE',
};

/**
 * HTTP status codes with semantic names.
 * Mirrors the response.js helpers for documentation purposes.
 * @type {Record<string, number>}
 */
const HTTP_STATUS = {
  OK:                   200,
  CREATED:              201,
  NO_CONTENT:           204,
  BAD_REQUEST:          400,
  UNAUTHORIZED:         401,
  FORBIDDEN:            403,
  NOT_FOUND:            404,
  CONFLICT:             409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS:    429,
  INTERNAL_SERVER_ERROR:500,
  SERVICE_UNAVAILABLE:  503,
};

module.exports = { ERROR_CODES, HTTP_STATUS };
