packages:
  - "packages/*" # shared-utils, constants (and any future server-side packages)
  - "backend"
  - "frontend/hub"
  - "frontend/game"
  - "frontend/trade"
  - "frontend/dating"
  - "frontend/sports"
  - "frontend/admin-dashboard"
  - "frontend/shared-ui"
  - "shared-types"
  - "scripts"

allowBuilds:
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  core-js: set this to true or false
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
